# pubspec.yaml
name: calorie_snap
description: A food calorie estimation app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  camera: ^0.10.0+1
  path: ^1.8.1
  provider: ^6.0.3
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/